export const symbols = [
    { id: 1, name: 'apple', image: '/Images/apple.png', value: 'apple', isFlipped: false, isMatched: false },
    { id: 2, name: 'apple', image: '/Images/apple.png', value: 'apple', isFlipped: false, isMatched: false },
    { id: 3, name: 'bananas', image: '/Images/bananas.png', value: 'bananas', isFlipped: false, isMatched: false },
    { id: 4, name: 'bananas', image: '/Images/bananas.png', value: 'bananas', isFlipped: false, isMatched: false },
    { id: 5, name: 'lemon', image: '/Images/lemon.png', value: 'lemon', isFlipped: false, isMatched: false },
    { id: 6, name: 'lemon', image: '/Images/lemon.png', value: 'lemon', isFlipped: false, isMatched: false },
    { id: 7, name: 'orange', image: '/Images/orange.png', value: 'orange', isFlipped: false, isMatched: false },
    { id: 8, name: 'orange', image: '/Images/orange.png', value: 'orange', isFlipped: false, isMatched: false },
    { id: 9, name: 'passion-fruit', image: '/Images/passion-fruit.png', value: 'passion-fruit', isFlipped: false, isMatched: false },
    { id: 10, name: 'passion-fruit', image: '/Images/passion-fruit.png', value: 'passion-fruit', isFlipped: false, isMatched: false },
    { id: 11, name: 'pineapple', image: '/Images/pineapple.png', value: 'pineapple', isFlipped: false, isMatched: false },
    { id: 12, name: 'pineapple', image: '/Images/pineapple.png', value: 'pineapple', isFlipped: false, isMatched: false },
    { id: 13, name: 'strawberry', image: '/Images/strawberry.png', value: 'strawberry', isFlipped: false, isMatched: false },
    { id: 14, name: 'strawberry', image: '/Images/strawberry.png', value: 'strawberry', isFlipped: false, isMatched: false },
    { id: 15, name: 'watermelon', image: '/Images/watermelon.png', value: 'watermelon', isFlipped: false, isMatched: false },
    { id: 16, name: 'watermelon', image: '/Images/watermelon.png', value: 'watermelon', isFlipped: false, isMatched: false },
    { id: 17, name: 'dragon-fruit', image: '/Images/dragon-fruit.png', value: 'dragon-fruit', isFlipped: false, isMatched: false },
    { id: 18, name: 'dragon-fruit', image: '/Images/dragon-fruit.png', value: 'dragon-fruit', isFlipped: false, isMatched: false },
];
